//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datacomp.StronaFirmowa.Fundament.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datacomp.StronaFirmowa.Fundament.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skontaktuj się.
        /// </summary>
        public static string About_CTA_Contact {
            get {
                return ResourceManager.GetString("About_CTA_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobacz produkt.
        /// </summary>
        public static string About_CTA_Product {
            get {
                return ResourceManager.GetString("About_CTA_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skontaktuj się z nami i dowiedz się, jak możemy wspierać rozwój Twojej firmy.
        /// </summary>
        public static string About_CTA_Subtitle {
            get {
                return ResourceManager.GetString("About_CTA_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dołącz do grona zadowolonych klientów.
        /// </summary>
        public static string About_CTA_Title {
            get {
                return ResourceManager.GetString("About_CTA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadowolonych klientów.
        /// </summary>
        public static string About_HappyClients {
            get {
                return ResourceManager.GetString("About_HappyClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ułatwiamy zarządzanie kadrami i płacami poprzez dostarczanie intuicyjnych, nowoczesnych i niezawodnych narzędzi informatycznych. Wierzymy, że technologia powinna być wsparciem, a nie przeszkodą w codziennej pracy..
        /// </summary>
        public static string About_MissionText {
            get {
                return ResourceManager.GetString("About_MissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasza Misja.
        /// </summary>
        public static string About_OurMission {
            get {
                return ResourceManager.GetString("About_OurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasza Historia.
        /// </summary>
        public static string About_OurStory {
            get {
                return ResourceManager.GetString("About_OurStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasz Zespół.
        /// </summary>
        public static string About_OurTeam {
            get {
                return ResourceManager.GetString("About_OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasze Wartości.
        /// </summary>
        public static string About_OurValues {
            get {
                return ResourceManager.GetString("About_OurValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasza Wizja.
        /// </summary>
        public static string About_OurVision {
            get {
                return ResourceManager.GetString("About_OurVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nas - Data-Comp.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrealizowanych projektów.
        /// </summary>
        public static string About_ProjectsCompleted {
            get {
                return ResourceManager.GetString("About_ProjectsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadowolenie klientów.
        /// </summary>
        public static string About_Satisfaction {
            get {
                return ResourceManager.GetString("About_Satisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-Comp powstała z pasji do automatyzacji procesów biznesowych. Od ponad dwóch dekad pomagamy firmom w cyfrowej transformacji zarządzania zasobami ludzkimi..
        /// </summary>
        public static string About_StoryText1 {
            get {
                return ResourceManager.GetString("About_StoryText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęliśmy jako mały zespół programistów i specjalistów HR, którzy wierzyli, że nowoczesne technologie mogą znacząco ułatwić pracę działów kadrowych w Polsce..
        /// </summary>
        public static string About_StoryText2 {
            get {
                return ResourceManager.GetString("About_StoryText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziś jesteśmy jednym z wiodących dostawców oprogramowania kadrowo-płacowego, obsługującym ponad 500 firm z różnych branż. Naszą siłą jest ciągły rozwój i dostosowywanie produktów do zmieniających się przepisów i potrzeb rynku..
        /// </summary>
        public static string About_StoryText3 {
            get {
                return ResourceManager.GetString("About_StoryText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponad 20 lat doświadczenia w tworzeniu innowacyjnych rozwiązań kadrowo-płacowych.
        /// </summary>
        public static string About_Subtitle {
            get {
                return ResourceManager.GetString("About_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zespół Developerów.
        /// </summary>
        public static string About_Team_Developers {
            get {
                return ResourceManager.GetString("About_Team_Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doświadczeni programiści tworzący stabilne i skalowalne rozwiązania.
        /// </summary>
        public static string About_Team_DevelopersDesc {
            get {
                return ResourceManager.GetString("About_Team_DevelopersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specjaliści HR.
        /// </summary>
        public static string About_Team_HR {
            get {
                return ResourceManager.GetString("About_Team_HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksperci w dziedzinie prawa pracy i procesów kadrowo-płacowych.
        /// </summary>
        public static string About_Team_HRDesc {
            get {
                return ResourceManager.GetString("About_Team_HRDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doradcy Biznesowi.
        /// </summary>
        public static string About_Team_Sales {
            get {
                return ResourceManager.GetString("About_Team_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomagamy wybrać najlepsze rozwiązanie dla Twojej firmy.
        /// </summary>
        public static string About_Team_SalesDesc {
            get {
                return ResourceManager.GetString("About_Team_SalesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wsparcie Techniczne.
        /// </summary>
        public static string About_Team_Support {
            get {
                return ResourceManager.GetString("About_Team_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zespół gotowy pomóc w każdej sytuacji, 5 dni w tygodniu.
        /// </summary>
        public static string About_Team_SupportDesc {
            get {
                return ResourceManager.GetString("About_Team_SupportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupa pasjonatów z wieloletnim doświadczeniem w branży IT i HR.
        /// </summary>
        public static string About_TeamSubtitle {
            get {
                return ResourceManager.GetString("About_TeamSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznaj Data-Comp.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient w centrum.
        /// </summary>
        public static string About_Value_Customer {
            get {
                return ResourceManager.GetString("About_Value_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Każda funkcjonalność powstaje z myślą o realnych potrzebach naszych użytkowników..
        /// </summary>
        public static string About_Value_CustomerText {
            get {
                return ResourceManager.GetString("About_Value_CustomerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doskonałość.
        /// </summary>
        public static string About_Value_Excellence {
            get {
                return ResourceManager.GetString("About_Value_Excellence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stawiamy na najwyższą jakość kodu, dokumentacji i obsługi klienta..
        /// </summary>
        public static string About_Value_ExcellenceText {
            get {
                return ResourceManager.GetString("About_Value_ExcellenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozwój.
        /// </summary>
        public static string About_Value_Growth {
            get {
                return ResourceManager.GetString("About_Value_Growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inwestujemy w rozwój zespołu i technologii, aby być zawsze o krok przed konkurencją..
        /// </summary>
        public static string About_Value_GrowthText {
            get {
                return ResourceManager.GetString("About_Value_GrowthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innowacyjność.
        /// </summary>
        public static string About_Value_Innovation {
            get {
                return ResourceManager.GetString("About_Value_Innovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieustannie rozwijamy nasze produkty, śledząc najnowsze trendy technologiczne i potrzeby rynku..
        /// </summary>
        public static string About_Value_InnovationText {
            get {
                return ResourceManager.GetString("About_Value_InnovationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejrzystość.
        /// </summary>
        public static string About_Value_Transparency {
            get {
                return ResourceManager.GetString("About_Value_Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jasne zasady współpracy, czytelne cenniki i otwarta komunikacja z klientami..
        /// </summary>
        public static string About_Value_TransparencyText {
            get {
                return ResourceManager.GetString("About_Value_TransparencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaufanie.
        /// </summary>
        public static string About_Value_Trust {
            get {
                return ResourceManager.GetString("About_Value_Trust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budujemy długotrwałe relacje oparte na rzetelności, przejrzystości i profesjonalizmie..
        /// </summary>
        public static string About_Value_TrustText {
            get {
                return ResourceManager.GetString("About_Value_TrustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Być pierwszym wyborem dla firm poszukujących kompleksowych rozwiązań HR. Chcemy, aby Komax 2.0 stał się standardem w branży, wyznaczającym kierunki rozwoju nowoczesnego zarządzania zasobami ludzkimi..
        /// </summary>
        public static string About_VisionText {
            get {
                return ResourceManager.GetString("About_VisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat doświadczenia.
        /// </summary>
        public static string About_YearsExperience {
            get {
                return ResourceManager.GetString("About_YearsExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wspieramy organizacje każdej wielkości w cyfrowej transformacji procesów kadrowo-płacowych.
        /// </summary>
        public static string Clients_Subtitle {
            get {
                return ResourceManager.GetString("Clients_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaufali nam.
        /// </summary>
        public static string Clients_TrustedBy {
            get {
                return ResourceManager.GetString("Clients_TrustedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-Comp.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system kadrowo-płacowy.
        /// </summary>
        public static string Company_Tagline {
            get {
                return ResourceManager.GetString("Company_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul. Przykładowa 123, 00-000 Warszawa.
        /// </summary>
        public static string Footer_Address {
            get {
                return ResourceManager.GetString("Footer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksowy system kadrowo-płacowy wspierający procesy HR w firmach każdej wielkości..
        /// </summary>
        public static string Footer_CompanyDescription {
            get {
                return ResourceManager.GetString("Footer_CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Footer_Contact {
            get {
                return ResourceManager.GetString("Footer_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszelkie prawa zastrzeżone.
        /// </summary>
        public static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polityka Prywatności.
        /// </summary>
        public static string Footer_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Footer_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szybkie linki.
        /// </summary>
        public static string Footer_QuickLinks {
            get {
                return ResourceManager.GetString("Footer_QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasoby.
        /// </summary>
        public static string Footer_Resources {
            get {
                return ResourceManager.GetString("Footer_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulamin.
        /// </summary>
        public static string Footer_TermsOfService {
            get {
                return ResourceManager.GetString("Footer_TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaufane rozwiązanie dla Twojej firmy.
        /// </summary>
        public static string Footer_TrustedSolution {
            get {
                return ResourceManager.GetString("Footer_TrustedSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nas.
        /// </summary>
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Nav_Blog {
            get {
                return ResourceManager.GetString("Nav_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strefa Klienta.
        /// </summary>
        public static string Nav_ClientZone {
            get {
                return ResourceManager.GetString("Nav_ClientZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Nav_Contact {
            get {
                return ResourceManager.GetString("Nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentacja.
        /// </summary>
        public static string Nav_Documentation {
            get {
                return ResourceManager.GetString("Nav_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Nav_FAQ {
            get {
                return ResourceManager.GetString("Nav_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona Główna.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string Nav_Product {
            get {
                return ResourceManager.GetString("Nav_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komax.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komax 2.0.
        /// </summary>
        public static string Product_Version {
            get {
                return ResourceManager.GetString("Product_Version", resourceCulture);
            }
        }
    }
}
